# Generated by Django 4.1 on 2022-08-31 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='issue_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
