# Generated by Django 4.1 on 2022-09-01 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0004_rename_project_id_contributor_project_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='author_user_id',
            new_name='contrib_users',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='comment_id',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='issue_id',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_id',
        ),
    ]
