# Generated by Django 4.1 on 2022-08-31 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0004_alter_issue_assignee_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='permission',
            field=models.CharField(choices=[('restricted', 'Contributeur'), ('all', 'Auteur')], default='restricted', max_length=50),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='role',
            field=models.CharField(choices=[('RES', 'Responsable'), ('AUT', 'Auteur'), ('CON', 'Contributeur')], default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='issue',
            name='priority',
            field=models.CharField(choices=[('Low', 'L'), ('Middle', 'M'), ('High', 'H')], default='Low', max_length=20),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('Ouvert', 'OPEN'), ('En cours', 'IN PROGRESS'), ('Terminé', 'Closed')], default='Ouvert', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('Web', 'Web'), ('iOS', 'iOS'), ('And', 'Android')], max_length=7),
        ),
    ]
