# Generated by Django 4.1 on 2022-09-05 08:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('issues', '0005_rename_author_user_id_project_contrib_users_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='contrib_users',
        ),
        migrations.AddField(
            model_name='project',
            name='author_user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
