# Generated by Django 4.1 on 2022-08-31 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0005_alter_contributor_permission_alter_contributor_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='priority',
            field=models.CharField(choices=[('L', 'Low'), ('M', 'Medium'), ('H', 'High')], default='L', max_length=20),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('OP', 'OPEN'), ('IP', 'IN PROGRESS'), ('CL', 'Closed')], default='Ouvert', max_length=20),
        ),
    ]
