# Generated by Django 4.1 on 2022-09-01 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0007_alter_comment_author_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('Back', 'Backend'), ('Front', 'Frontend'), ('iOS', 'iOS'), ('And', 'Android')], max_length=7),
        ),
    ]
