# Generated by Django 4.1 on 2022-09-05 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0007_rename_author_user_id_project_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('Backend', 'Back'), ('Frontend', 'Front'), ('iOS', 'iOS'), ('Android', 'And')], max_length=8),
        ),
    ]
