# Generated by Django 4.1 on 2022-09-05 09:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('issues', '0008_alter_project_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='contrib_users',
            field=models.ManyToManyField(blank=True, related_name='projects', through='issues.Contributor', to=settings.AUTH_USER_MODEL),
        ),
    ]
