# Generated by Django 4.1 on 2022-09-01 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0008_alter_project_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='author_user_id',
        ),
        migrations.AddField(
            model_name='project',
            name='author_user_id',
            field=models.ManyToManyField(related_name='projects', to='issues.contributor'),
        ),
    ]
