# Generated by Django 4.1 on 2022-09-01 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0009_remove_project_author_user_id_project_author_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='role',
            field=models.CharField(choices=[('RESP', 'Responsable'), ('AUTH', 'Auteur'), ('CONT', 'Contributeur')], default='', max_length=12),
        ),
    ]
