# Generated by Django 4.1 on 2022-09-07 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0011_alter_project_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='author',
        ),
    ]
