# Generated by Django 4.1 on 2022-09-08 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0014_project_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='author',
            new_name='author_user_id',
        ),
    ]
