# Generated by Django 4.1 on 2022-09-08 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0015_rename_author_project_author_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='contrib_users',
        ),
    ]
