# Generated by Django 4.1 on 2022-09-08 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0016_remove_project_contrib_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='author_user_id',
            new_name='author',
        ),
    ]
