# Generated by Django 4.1 on 2022-09-08 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0017_rename_author_user_id_project_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='author',
        ),
    ]
