# Generated by Django 4.1 on 2022-09-12 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0023_alter_project_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author_user_id',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='issue',
            old_name='assignee_user_id',
            new_name='assignee',
        ),
        migrations.RenameField(
            model_name='issue',
            old_name='author_user_id',
            new_name='author',
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('OP', 'OPEN'), ('IP', 'IN PROGRESS'), ('CL', 'Closed')], default='OPEN', max_length=20),
        ),
    ]
