# Generated by Django 4.1 on 2022-09-12 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0026_alter_comment_issue_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='issue_id',
            new_name='issue',
        ),
    ]
